# Test against the latest version of this Node.js version
environment:
  nodejs_version: "8"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install -g vsce
  - npm install
  - npm run vscode:prepublish

build_script:
  - vsce package

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  - node ./node_modules/vscode/bin/test

# Don't actually build.
#build: off
